In [30]:
kanto = [75,78,80]

In [31]:
w1 = 0.5
w2 = 0.6
w3 = 0.4
weight = [w1,w2,w3]

In [32]:
kanto_weight = list()
result = 0
for x,y in zip(kanto,weight):
    kanto_weight.append(x*y)
print(kanto_weight)

[37.5, 46.8, 32.0]


In [33]:
print(sum(kanto_weight))

116.3


NUMPY

In [34]:
import numpy as np

In [6]:
np_kanto = np.array([75,78,80])

In [7]:
np_weight = np.array([w1,w2,w3])

In [8]:
print(np_kanto)
print(type(np_kanto))

[75 78 80]
<class 'numpy.ndarray'>


In [9]:
i = 0
print(type(i))

<class 'int'>


In [10]:
result = np.dot(np_kanto,weight)
print(result)

116.3


In [11]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----

In [12]:
np_result = np_kanto * np_weight
np_result

array([37.5, 46.8, 32. ])

In [13]:
np_result.sum()

116.3

In [14]:
sum(np_result)

116.3

In [15]:
kanto_weight.sum()

AttributeError: 'list' object has no attribute 'sum'

numpy vs normal computations

In [16]:
arr1 = range(1000000)
arr2 = range(1000000,2000000)

np_arr1 = np.array(arr1)
np_arr2 = np.array(arr2)

In [17]:
%%time
result = 0
for x,y in zip(arr1,arr2):
    result += x*y
print(result)

833332333333500000
CPU times: total: 141 ms
Wall time: 126 ms


In [18]:
%%time
result = np.dot(np_arr1,np_arr2)
print(result)

-1942957984
CPU times: total: 0 ns
Wall time: 3 ms


Dimensions of array

In [19]:
# 1D array
arr1 = np.array([1,2,3])

In [20]:
arr1.shape

(3,)

In [21]:
arr1.dtype

dtype('int32')

In [22]:
# 2D array
arr2 = np.array( [ [ 1, 2, 3],
                   [ 4, 5, 6],
                   [ 7, 8, 9],
                   [10,11,12] 
                 ] )

In [23]:
arr2.shape

(4, 3)

In [24]:
arr2.dtype

dtype('int32')

In [25]:
# 3D array
arr3 = np.array( [ [ 
                     [ 1, 2, 3],
                     [ 4, 5, 6] 
                   ],
                   [ 
                     [ 7, 8, 9],
                     [10,11,12] 
                   ],
                   [ 
                     [13,14,15],
                     [16,17,18] 
                   ]
                 ] )

In [26]:
arr3.shape

(3, 2, 3)

In [27]:
arr3.dtype

dtype('int32')

In [28]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


Working with CSV files

In [ ]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

In [35]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [36]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [37]:
weights = np.array([0.3,0.2,0.5])

In [38]:
climate_data.shape

(10000, 3)

In [39]:
yields = climate_data @ weights #matrix multiplication

In [40]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [41]:
yields.shape

(10000,)

In [43]:
climate_result = np.concatenate((climate_data, yields.reshape(10000,1)), axis = 1)

In [44]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [45]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

In [46]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
 

In [48]:
help(reshape)

NameError: name 'reshape' is not defined

In [51]:
np.savetxt('climate_result.txt',
          climate_result,
           fmt = '%.2f',
          header = 'temperature,rainfall,humidity,yields_of_apples',
           comments = ''
          )

Arithmetic and Logical operations 

In [53]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

In [54]:
arr2 = np.array([[4,5,6],
                 [7,8,9]])

In [55]:
#scalar addition
arr1 + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [57]:
#scalar multiplication
arr2 * 2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [58]:
#scalar power
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [59]:
#element wise operations
arr1 + arr2

array([[ 5,  7,  9],
       [11, 13, 15]])

In [61]:
arr1 - arr2
arr1 / arr2

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667]])

In [62]:
arr1 * arr2

array([[ 4, 10, 18],
       [28, 40, 54]])

In [63]:
#comparisons 
#it returns a list of boolean

In [64]:
 arr3 = np.array([[1,4,7,0],
                  [3,6,8,9]])

In [65]:
arr4 = np.array([[1,2,8,0],
                 [4,6,7,9]])

In [66]:
arr3 == arr4

array([[ True, False, False,  True],
       [False,  True, False,  True]])

In [67]:
arr3 != arr4

array([[False,  True,  True, False],
       [ True, False,  True, False]])

In [68]:
arr3 < arr4

array([[False, False,  True, False],
       [ True, False, False, False]])

In [69]:
arr3 >= arr4

array([[ True,  True, False,  True],
       [False,  True,  True,  True]])

Indicing and Slicing

In [83]:
arr1 = np.array([[[ 1, 2, 3, 4],
                  [ 5, 6, 7,80]],             
         
                 [[12,13,14,15],
                  [11,21,34,55]],             

                 [[43,54, 5,67],
                  [67,89,90,19]]])          

In [84]:
type(arr1)

numpy.ndarray

In [85]:
arr1[1]

array([[12, 13, 14, 15],
       [11, 21, 34, 55]])

In [86]:
arr1[0,1,1]

6

In [87]:
arr1[0, 1, 1]

6

In [88]:
arr1[2:,:,0]

array([[43, 67]])

In [89]:
arr1[1:,:,2]

array([[14, 34],
       [ 5, 90]])

In [90]:
arr1[1:,:2,2:]

array([[[14, 15],
        [34, 55]],

       [[ 5, 67],
        [90, 19]]])

In [91]:
arr1[1:,:2]

array([[[12, 13, 14, 15],
        [11, 21, 34, 55]],

       [[43, 54,  5, 67],
        [67, 89, 90, 19]]])

Other ways to create np array

In [92]:
np.zeros((3,4))#dimensions are given in tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [95]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [96]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [98]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [100]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
np.eye(5,dtype = bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [108]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [113]:
np.random.rand(5)

array([0.54639184, 0.55936455, 0.22047446, 0.61408098, 0.3076997 ])

In [114]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [117]:
np.random.randn(5)      

array([ 0.39190285, -1.18928765, -0.72119285, -1.27043503, -0.43892402])

In [118]:
np.full([3,4],9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [126]:
np.linspace(4,88,8)

array([ 4., 16., 28., 40., 52., 64., 76., 88.])

In [127]:
np.arange(12,60,5)

array([12, 17, 22, 27, 32, 37, 42, 47, 52, 57])